const RECEIVE_API_DATA = "RECEIVE_API_DATA";
const REQUEST_API_DATA = "REQUEST_API_DATA";
const LOGOUT = 'LOGOUT'
const LOGIN = 'LOGIN'
const HITLOGIN = 'HITLOGIN'
const HITLOGOUT = 'HITLOGOUT'
const HITFORGOTMPIN = 'HITFORGOTMPIN'
const LOGINERROR = 'LOGINERROR'
const APPARREL_API_ERROR = 'APPARREL_API_ERROR'
const HIT_WHISLIST = 'HIT_WHISLIST'
const ADD_WHISLIST = 'ADD_WHISLIST'
const REMOVE_WHISLIST = 'REMOVE_WHISLIST'

export { RECEIVE_API_DATA, REQUEST_API_DATA, LOGOUT, LOGIN, HITLOGIN, HITLOGOUT, HITFORGOTMPIN, LOGINERROR,
    APPARREL_API_ERROR, HIT_WHISLIST, ADD_WHISLIST, REMOVE_WHISLIST }
