const RECEIVE_API_DATA = "RECEIVE_API_DATA";
const REQUEST_API_DATA = "REQUEST_API_DATA";
const LOGOUT = 'LOGOUT'
const LOGIN = 'LOGIN'
const HITLOGIN = 'HITLOGIN'
const HITLOGOUT = 'HITLOGOUT'
const HITFORGOTMPIN = 'HITFORGOTMPIN'
const LOGINERROR = 'LOGINERROR'
const APPARREL_API_ERROR = 'APPARREL_API_ERROR'
const HIT_WHISLIST = 'HIT_WHISLIST'
const ADD_WHISLIST = 'ADD_WHISLIST'
const REMOVE_WHISLIST = 'REMOVE_WHISLIST'
const HIT_CART = 'HIT_CART'
const ADD_CART = 'ADD_CART'
const REMOVE_CART = 'REMOVE_CART'
const HIT_APPARREL_COUNT = 'HIT_APPARREL_COUNT'
const ADD_APPARREL_COUNT = 'ADD_APPARREL_COUNT'
const REMOVE_APPARREL_COUNT = 'REMOVE_APPARREL_COUNT'

export { RECEIVE_API_DATA, REQUEST_API_DATA, LOGOUT, LOGIN, HITLOGIN, HITLOGOUT, HITFORGOTMPIN, LOGINERROR,
    APPARREL_API_ERROR, HIT_WHISLIST, ADD_WHISLIST, REMOVE_WHISLIST, HIT_CART, ADD_CART, REMOVE_CART,
    HIT_APPARREL_COUNT, ADD_APPARREL_COUNT, REMOVE_APPARREL_COUNT }
